version: '3.9'
services:

  app:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=f1_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always